In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/druth/Downloads/undated_dataset_NYVRA.csv")
df.head()

C:\Users\druth\AppData\Local\Temp\ipykernel_3504\1537757886.py:3: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/druth/Downloads/undated_dataset_NYVRA.csv")

,District_Name,UnitName,FIR_YEAR,FIR_MONTH,Unnamed: 4,FIR_Day,FIR Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,...,Distance from PS,Beat_Name,Village_Area_Name,Accused Count,Arrested Male,Arrested Female,Arrested Count\tNo.,Accused_ChargeSheeted Count,Conviction Count,Unit_ID
0,Bagalkot,Guledagudda PS,2016,11,NaN,4,Non Heinous,Dis/Acq,Sue-moto by Police,KARNATAKA POLICE ACT 1963,...,EAST 3 KM,TOWN BEAT NO 01,NEGLI PETE,1,1,0,1,1,0,1249
1,Bagalkot,Guledagudda PS,2016,11,NaN,5,Non Heinous,Compounded,Sue-moto by Police,CrPC,...,WEST 10 KM,RURAL BEAT NO 04,Lingapur,2,0,0,0,2,0,1249
2,Bagalkot,Guledagudda PS,2016,11,NaN,7,Non Heinous,Pending Trial,Sue-moto by Police,Karnataka State Local Act,...,SOTUH 15 KM,RURAL BEAT NO 02,kotnalli,1,1,0,1,1,0,1249
3,Bagalkot,Guledagudda PS,2016,11,NaN,7,Non Heinous,Dis/Acq,Sue-moto by Police,Karnataka State Local Act,...,SOUTH 15 KM,RURAL BEAT NO 02,kotnalli,1,1,0,1,1,0,1249
4,Bagalkot,Guledagudda PS,2016,11,NaN,8,Non Heinous,BoundOver,Sue-moto by Police,CrPC,...,WEST 15 KM,RURAL BEAT NO 04,Lingapur,1,1,0,1,1,0,1249

In [3]:
df.shape

(1038576, 28)

In [11]:
df.columns

Index(['District_Name', 'UnitName', 'FIR_YEAR', 'FIR_MONTH', 'FIR_Day',
       'FIR Type', 'FIR_Stage', 'Complaint_Mode', 'CrimeGroup_Name',
       'CrimeHead_Name', 'Latitude', 'Longitude', 'ActSection', 'KGID',
       'Internal_IO', 'Place of Offence', 'Distance from PS', 'Beat_Name',
       'Village_Area_Name', 'Accused Count', 'Arrested Male',
       'Arrested Female', 'Arrested Count\tNo.', 'Accused_ChargeSheeted Count',
       'Conviction Count', 'Unit_ID'],
      dtype='object')

In [12]:
df.isnull().sum()

District_Name                      0
UnitName                           0
FIR_YEAR                           0
FIR_MONTH                          0
FIR_Day                            0
FIR Type                           0
FIR_Stage                          0
Complaint_Mode                     0
CrimeGroup_Name                    0
CrimeHead_Name                     0
Latitude                       69450
Longitude                      69450
ActSection                         0
KGID                               0
Internal_IO                        0
Place of Offence                   0
Distance from PS                   0
Beat_Name                          0
Village_Area_Name                  0
Accused Count                      0
Arrested Male                      0
Arrested Female                    0
Arrested Count\tNo.                0
Accused_ChargeSheeted Count        0
Conviction Count                   0
Unit_ID                            0
dtype: int64

In [13]:
df = df.dropna()
df.isnull().sum()

District_Name                  0
UnitName                       0
FIR_YEAR                       0
FIR_MONTH                      0
FIR_Day                        0
FIR Type                       0
FIR_Stage                      0
Complaint_Mode                 0
CrimeGroup_Name                0
CrimeHead_Name                 0
Latitude                       0
Longitude                      0
ActSection                     0
KGID                           0
Internal_IO                    0
Place of Offence               0
Distance from PS               0
Beat_Name                      0
Village_Area_Name              0
Accused Count                  0
Arrested Male                  0
Arrested Female                0
Arrested Count\tNo.            0
Accused_ChargeSheeted Count    0
Conviction Count               0
Unit_ID                        0
dtype: int64

In [14]:
df.dtypes

District_Name                   object
UnitName                        object
FIR_YEAR                         int64
FIR_MONTH                        int64
FIR_Day                          int64
FIR Type                        object
FIR_Stage                       object
Complaint_Mode                  object
CrimeGroup_Name                 object
CrimeHead_Name                  object
Latitude                       float64
Longitude                      float64
ActSection                      object
KGID                            object
Internal_IO                      int64
Place of Offence                object
Distance from PS                object
Beat_Name                       object
Village_Area_Name               object
Accused Count                    int64
Arrested Male                    int64
Arrested Female                  int64
Arrested Count\tNo.              int64
Accused_ChargeSheeted Count      int64
Conviction Count                 int64
Unit_ID                          int64
dtype: object

In [15]:
df.duplicated().sum()

27197

In [16]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [17]:
df['FIR_MONTH'].between(1, 12).all()

True

In [18]:
df['FIR_Day'].between(1, 31).all()

True

In [30]:
(df['Arrested_Count'] <= df['Accused_Count']).all()

False

In [31]:
(df['Arrested_Count'] > df['Accused_Count']).sum()

53035

In [33]:
df[df['Arrested_Count'] > df['Accused_Count']]

,District_Name,UnitName,FIR_YEAR,FIR_MONTH,FIR_Day,FIR_Type,FIR_Stage,Complaint_Mode,CrimeGroup_Name,CrimeHead_Name,...,Distance_from_PS,Beat_Name,Village_Area_Name,Accused_Count,Arrested_Male,Arrested_Female,Arrested_Count,Accused_ChargeSheeted_Count,Conviction_Count,Unit_ID
22,Bagalkot,Guledagudda PS,2017,1,20,Non Heinous,Pending Trial,Sue-moto by Police,Karnataka State Local Act,Karnataka Excise Act 1965,...,EAST 8 KM,RURAL BEAT NO 02,kotnalli,0,1,0,1,1,0,1249
23,Bagalkot,Guledagudda PS,2017,1,20,Non Heinous,Pending Trial,Sue-moto by Police,Karnataka State Local Act,Karnataka Excise Act 1965,...,EAST 15 KM,RURAL BEAT NO 02,kotnalli,0,2,0,2,2,0,1249
40,Bagalkot,Guledagudda PS,2017,2,24,Non Heinous,Convicted,Sue-moto by Police,Karnataka State Local Act,Mmdr (Mines & Minerals Regulation Development)...,...,WEST 8 KM,RURAL BEAT NO 04,Lingapur,1,2,0,2,2,2,1249
41,Bagalkot,Guledagudda PS,2017,2,27,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Street Gambling (87),...,EAST 3 KM,RURAL BEAT NO 01,pavratI village,7,8,0,8,8,8,1249
42,Bagalkot,Guledagudda PS,2017,2,27,Non Heinous,Convicted,Sue-moto by Police,KARNATAKA POLICE ACT 1963,Street Gambling (87),...,WEST 12 KM,RURAL BEAT NO 04,Lingapur,4,6,0,6,6,6,1249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038526,Kalaburagi,Sedam PS,2019,8,16,Non Heinous,Pending Trial,Written,THEFT,Of Automobiles - Of Two Wheelers,...,1 KM TOWARDS EAST,Beat No 34,DODDA AGASI AREA SEDAM,0,2,0,2,2,0,1585
1038537,Kalaburagi,Sedam PS,2019,9,5,Non Heinous,Convicted,Oral,MOTOR VEHICLE ACCIDENTS NON-FATAL,State Highways,...,SOUTH 9 KM FROM PS,Beat No 37,UDAGI CROSS AREA SEDAM,0,1,0,1,1,1,1585
1038548,Kalaburagi,Sedam PS,2019,9,19,Non Heinous,Pending Trial,Sue-moto by Police,Karnataka State Local Act,Mmdr (Mines & Minerals Regulation Development)...,...,1 KM TOWARDS WEST,Beat No 36,Ashraya Colony,1,2,0,2,2,0,1585
1038557,Kalaburagi,Sedam PS,2019,10,3,Non Heinous,Convicted,Sue-moto by Police,Karnataka State Local Act,Mmdr (Mines & Minerals Regulation Development)...,...,SOUTH 16 KM FROM PS,Beat No 16,RANJOL,1,2,0,2,2,2,1585
1038559,Kalaburagi,Sedam PS,2019,10,4,Non Heinous,Convicted,Oral,MOTOR VEHICLE ACCIDENTS NON-FATAL,State Highways,...,6 KM TOWARDS SOUTH,Beat No 13,BATAGERA K,0,1,0,1,1,1,1585

In [36]:
(df['Arrested_Count'] <= df['Accused_Count']).all()

True

In [38]:
df = df.rename(columns={
    'FIR_YEAR': 'year',
    'FIR_MONTH': 'month',
    'FIR_Day': 'day'
})

In [39]:
df['Date'] = pd.to_datetime(df[['year', 'month', 'day']])
df[['year','month','day','Date']].head()

   year  month  day       Date
0  2016     11    4 2016-11-04
1  2016     11    5 2016-11-05
2  2016     11    7 2016-11-07
3  2016     11    7 2016-11-07
4  2016     11    8 2016-11-08

In [40]:
df[['Latitude', 'Longitude']].describe()

            Latitude      Longitude
count  888894.000000  888894.000000
mean       13.838740      76.858560
std         1.438931       0.965985
min        11.666271      74.106156
25%        12.996545      76.124856
50%        13.022235      77.510184
75%        14.340942      77.567183
max        18.385949      78.571536